### ISSUE TITLE
Groovy console does not execute scripts with admin user

### ISSUE THREAD

**Issue by olimination** [icfnext/aem-groovy-console#102]
In the README file it is described that the admin user by default can execute scripts, but this somehow does not seem to work.

- Logged in as admin user in AEM
- Open /apps/groovyconsole.html
- Execute some script
- Error message appears: "You do not have permission to run scripts in the Groovy Console."

If we add an appropriate OSGi config for the "Groovy Console Service", then it works.

But according to the code here:
https://github.com/icfnext/aem-groovy-console/blob/7f3bc579aaa4f77510a5cf481429acd0d5be2102/src/main/groovy/com/icfolson/aem/groovy/console/configuration/impl/DefaultConfigurationService.groovy#L52

I actually assume that it should work.

Do I miss something or could this be some bug?

Tested with AEM 6.5.2.0

**Comment by lykorian** [comment]
This is fixed in the latest `develop` snapshot but has not been released yet.

**Comment by lykorian** [comment]
What version are you running?

**Comment by olimination** [comment]
Ah cool, version 14.0.0. Then we'll wait for the next version.

Thank you!
