### ISSUE TITLE
Please update jQuery and Moment frontend dependencies

### ISSUE THREAD

**Issue by wsatyla** [icfnext/aem-groovy-console#105]
The frontend dependencies used by the AEM Groovy Console are outdated. Please consider an upgrade of the following dependencies:
- jQuery 1.11.1 
- Moment 2.7.0

Because the above libraries contain security vulnerabilities, security scanners (e.g. Nexus IQ) treat the AEM Groovy Console as vulnerable.

**Comment by tomaszsoczyk-cognifide** [comment]
Hi all, any chance this beauty could be merged and released?

**Comment by toniedzwiedz** [comment]
@lykorian my team would find this update very useful as well. Is there any chance this could be prioritised? 
I saw the PR by @wsatyla and it does look sensible. Any way we could help?

**Comment by lykorian** [comment]
Done, release coming shortly

**Comment by tomaszsoczyk-cognifide** [comment]
Thanks @lykorian  - any rough idea when you think we could expect release (we need this awesome tool desperately - but we are right now forced to release our own version since without those dependencies updated we can't use the tool)

**Comment by markdaugherty** [comment]
It should happen tonight or tomorrow morning - unfortunately I'm dependent on someone in the ICF organization to release on my behalf since I'm no longer with the company.  The tag and master branch are already updated.

**Comment by markdaugherty** [comment]
It's done.

**Comment by tomaszsoczyk-cognifide** [comment]
Thank you very much!
