### ISSUE TITLE
Released artifacts not available 16.0.0

### ISSUE THREAD

**Issue by pun-ky** [icfnext/aem-groovy-console#108]
https://github.com/icfnext/aem-groovy-console/releases/tag/16.0.0 / tag available but seems that there are no artifacts published

awaiting https://mvnrepository.com/artifact/com.icfolson.aem.groovy.console/aem-groovy-console/16.0.0 [404]
to be available.

when it is planned to be available?

Greetings, Krystian

**Comment by markdaugherty** [comment]
https://search.maven.org/artifact/com.icfolson.aem.groovy.console/aem-groovy-console/16.0.0/jar

Not sure why it's unavailable at mvnrepository.com.  My projects are able to download the dependency from Maven central, however.

**Comment by pun-ky** [comment]
Ok thx 🙂
