### ISSUE TITLE
Make compatible with AEMaaCS

### ISSUE THREAD

**Issue by kwin** [icfnext/aem-groovy-console#113]
AEMaaCS has a restriction when it comes to the `/var` repository location: https://experienceleague.adobe.com/docs/experience-manager-learn/cloud-service/debugging/debugging-aem-as-a-cloud-service/build-and-deployment.html?lang=en#including-%2Fvar-in-content-package.

Therefore the content structure and ACLs below `/var` must be [created via repoinit](https://experienceleague.adobe.com/docs/experience-manager-cloud-service/implementing/deploying/overview.html?lang=en#mutable-content). For the samples I would recommend to just move them to an immutable location (`/apps/groovyconsole/samples`).

**Comment by markdaugherty** [comment]
Please see https://github.com/CID15/aem-groovy-console
