### ISSUE TITLE
Discussion: How to protect against malicious users' scripts (or, how to get Groovy Console approved for use in production)

### ISSUE THREAD

**Issue by paul-bjorkstrand** [icfnext/aem-groovy-console#80]
In Groovy, it is possible to blacklist certain coding patterns from being compiled using [SecureASTCustomizer](http://docs.groovy-lang.org/2.3.7/html/api/org/codehaus/groovy/control/customizers/SecureASTCustomizer.html). Initially, protecting against basic harmful code (e.g. `System.exit()`, using [`ResourceResolverFactory.getAdministrativeResourceResolver(..)`](https://sling.apache.org/apidocs/sling8/org/apache/sling/api/resource/ResourceResolverFactory.html#getAdministrativeResourceResolver-java.util.Map-) to get a generic administrative resource resolver, etc).

It would be nice to have a way to plug this in, to be more secure. On some projects, due to security concerns, they do not allow the Groovy Console to be used in certain environments (some going as far as not allowing it in *any* integrated environment). This would be a step along the way to make this tool secure enough to be used in production, everywhere.

If SecureASTCustomizer isn't enough, then a possible alternative could be http://groovy-sandbox.kohsuke.org/

**Comment by ahmed-musallam** [comment]
@lykorian how was this resolved? or was it closed by mistake?

**Comment by lykorian** [comment]
@ahmed-musallam see the new [`CompilationCustomizerExtensionProvider`](https://github.com/icfnext/aem-groovy-console/blob/develop/src/main/groovy/com/icfolson/aem/groovy/console/api/CompilationCustomizerExtensionProvider.groovy) service interface.
