### ISSUE TITLE
Content structure reorganisation prior to AEM 6.5

### ISSUE THREAD

**Issue by marcinczeczko** [icfnext/aem-groovy-console#82]
Starting from AEM 6.4 (see https://helpx.adobe.com/experience-manager/6-4/sites/deploying/using/repository-restructuring.html)  content repository is to be reorganised prior to 6.5, and finally in 6.5 most probably will follow the rule as below: 
- /etc should not be used (probably to be removed)
- any application code, clientlibs should be located under /apps
- any runtime data to be under /var or /content folder, while the configurations should be rather under /conf
The groovy console should have its own content structure to be reorganised as follows:
- /etc/clientlibs/groovyconsole should rather go to /apps/groovyconsole/clientlibs
- /etc/groovyconsole to /apps/groovyconsole
- /etc/groovyconsole/scripts should go to /conf/groovyconsole/scripts or /var/groovyconsole/scripts
- /etc/groovyconsole/jcr:content/audit should to to /var/groovyconsole/audit

**Comment by lykorian** [comment]
@marcinczeczko these changes have been implemented in the `develop` branch if you'd like to begin local testing.
