### ISSUE TITLE
Broken link in console's "Enhancements" collapsible

### ISSUE THREAD

**Issue by paul-bjorkstrand** [icfnext/aem-groovy-console#84]
https://github.com/icfnext/aem-groovy-console/blob/86d522cd760e2e8c039022af65732ebb80f7a569/src/main/content/jcr_root/apps/groovyconsole/components/console/enhancements.html#L9

Should be
`http://code.digitalatolson.com/aem-groovy-extension/groovydocs/com/icfolson/aem/groovy/extension/services/impl/DefaultMetaClassExtensionProvider.html`

I'll try to get a PR out there sometime next week if someone has not fixed it by then.

**Comment by lykorian** [comment]
Fixed - thank you.

**Comment by paul-bjorkstrand** [comment]
Thanks, I hadn't had a chance to revisit this yet, so thanks for getting this one :)
