### ISSUE TITLE
OSGi configuration option "Allowed Groups" (allowedGroups) does not allow empty list

### ISSUE THREAD

**Issue by kwin** [icfnext/aem-groovy-console#91]
In case nothing is configured no one has the privilege to run groovy scripts. Instead I get the error message `You do not have permission to run scripts in the Groovy Console.`.
Only if I explicitly grant access via the OSGi configuration `allowedGroups` to a  particular group it does work.
This contradicts the label of the OSGi configuration option and the documentation which states 
> List of group names that are authorized to use the console. If empty, no authorization check is performed. (allowedGroups)

**Comment by lykorian** [comment]
This was changed recently as the console is now "secure by default".  I've updated the documentation to reflect this.  Thanks.

**Comment by manidevaraj** [comment]
@lykorian I see the updated doc in for this change but OSGi configuration also needs an update.

![image](https://user-images.githubusercontent.com/20967269/69634090-8bc02700-1077-11ea-9d74-46c0ebbcacbb.png)
