### ISSUE TITLE
Permissions issue with AEM 6.5

### ISSUE THREAD

**Issue by viveksachdeva** [icfnext/aem-groovy-console#94]
I installed Groovy console version 14.0 on AEM 6.5 but while running any script, I am getting:
"You do not have permission to run scripts in the Groovy Console."
with requests to http://localhost:4502/bin/groovyconsole/post.json failing

**Comment by lykorian** [comment]
See https://github.com/icfnext/aem-groovy-console#osgi-configuration

_"List of group names that are authorized to use the console. Required. If empty, no script executions will be allowed."_
