### ISSUE TITLE
Request agnostic groovy console service script execution

### ISSUE THREAD

**Issue by pun-ky** [icfnext/aem-groovy-console#96]
I am developing some new tool which will have integration with Groovy Console.
The idea is for having scripts that could be pre-launched during bundle start lifecycle event.

However, AEM Groovy Console does not offer any method for running scripts without request specified. Should I use some request mock in that case or maybe you could do some work for extracting some code from

https://github.com/icfnext/aem-groovy-console/blob/develop/src/main/groovy/com/icfolson/aem/groovy/console/impl/DefaultGroovyConsoleService.groovy#L74

to separate groovy executing service method which will be request agnostic?

Any thoughts appreciated,

Greetings, Krystian.

PS some other tool integrating with Groovy Console also requires such feature and is doing some workaround, see:

* https://github.com/valtech/aem-easy-content-upgrade/blob/develop/core/src/main/java/de/valtech/aecu/core/service/AecuServiceImpl.java#L186
* https://github.com/valtech/aem-easy-content-upgrade/blob/develop/core/src/main/java/de/valtech/aecu/core/service/GroovyConsoleRequest.java

**Comment by lykorian** [comment]
@pun-ky see linked pull request - does this align with your expectations?

**Comment by pun-ky** [comment]
Looks mostly good. I am wondering only why request is a part of script context interface. While viewing this on mobile 📱 I cannot see usages 😉
